In [2]:
import numpy as np
import pandas as pd

In [6]:
pd.Series((1,2,3))

0    1
1    2
2    3
dtype: int64

In [12]:
pd.DataFrame({'A': 1., 'B': 'text', 'C': [1,2,4]})

A     B  C
0  1.0  text  1
1  1.0  text  2
2  1.0  text  4

In [15]:
df = pd.DataFrame(np.random.randn(5,3))
df

0         1         2
0  0.029569  1.437778  2.480111
1  0.389770  0.571173 -0.445387
2 -1.687134  0.258344  0.911580
3 -0.632197 -0.959918 -0.513917
4  0.284747  0.262861 -0.791723

In [20]:
print(df.index)
print(df.columns)
print(df.values)
print(type(df.values))

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=3, step=1)
[[ 0.02956917  1.43777838  2.48011121]
 [ 0.38976956  0.5711733  -0.44538652]
 [-1.68713377  0.25834374  0.91158027]
 [-0.63219733 -0.95991771 -0.5139165 ]
 [ 0.28474655  0.26286086 -0.79172293]]
<class 'numpy.ndarray'>


In [57]:
print(df.describe())
print(type(df.describe()))
# help(pd.period_range)

          money      time    reward
count  5.000000  5.000000  5.000000
mean   0.338331  0.472040  0.257123
std    1.027186  1.660097  1.359074
min   -0.628995 -1.547222 -1.364060
25%   -0.223191 -1.130512 -0.940734
50%   -0.124213  1.618601  0.529012
75%    0.712479  1.703934  1.470163
max    1.955577  1.715397  1.591232
<class 'pandas.core.frame.DataFrame'>


In [43]:
df = pd.DataFrame(np.random.randn(5,3), index=list('ABCDE'), columns=['money', 'time', 'reward'])
df

money      time    reward
A  1.955577  1.703934  1.591232
B  0.712479 -1.130512  1.470163
C -0.223191  1.715397 -0.940734
D -0.628995 -1.547222  0.529012
E -0.124213  1.618601 -1.364060

In [55]:
print(df.loc[:'C',['time', 'reward']])
print()
# print(df['A']) ERROR
print (df[1:2])
print()
print (df.loc['A'])
print()
print (df.iloc[1:4])

       time    reward
A  1.703934  1.591232
B -1.130512  1.470163
C  1.715397 -0.940734

      money      time    reward
B  0.712479 -1.130512  1.470163

money     1.955577
time      1.703934
reward    1.591232
Name: A, dtype: float64

      money      time    reward
B  0.712479 -1.130512  1.470163
C -0.223191  1.715397 -0.940734
D -0.628995 -1.547222  0.529012


In [60]:
print(len(df))
print(df.shape[0])
print(df.shape[1])
print(np.arange(2, 5))

5
5
3
[2 3 4]


In [72]:
lst=[1,2,3,1,2,3]
s = pd.Series([1,2,3,10,20,30], lst)
gb = s.groupby(level=0)
gb.sum()

1    11
2    22
3    33
dtype: int64

IndexError: list assignment index out of range