In [30]:
import numpy as np
import pandas as pd
import pprint

In [11]:
s0 = pd.Series((1,2,3))

In [9]:
s1 = pd.Series({'a': 12, 'b': 21, 's':1,'p':1000,'x':None})
print(s1)
print(s1.index)
print(s1[1:3])
print(s1[2:-1])

a      12.0
b      21.0
s       1.0
p    1000.0
x       NaN
dtype: float64
Index(['a', 'b', 's', 'p', 'x'], dtype='object')
b    21.0
s     1.0
dtype: float64
s       1.0
p    1000.0
dtype: float64


In [27]:
df0 = pd.DataFrame(s1)
df0

0
a    12.0
b    21.0
s     1.0
p  1000.0
x     NaN

In [20]:
dfA = pd.DataFrame({'A': range(3), 'B': 'text', 'C': [1,2,4]}, index=['one', 'two', 'three'])
print(dfA)
dfA[dfA['C'] == 2]

       A     B  C
one    0  text  1
two    1  text  2
three  2  text  4


A     B  C
two  1  text  2

In [25]:
df1 = pd.DataFrame(np.random.randn(5,3), columns=['weight', 'size', 'entropy'])
s2 = pd.Series([1,1,2], index=['weight', 'entropy','size'])
print(df1, s2, sep='\n\n')
print()
print(df1*s2)

     weight      size   entropy
0  1.162001  0.096956  0.547441
1 -1.398634 -0.644761 -0.667286
2  0.864093 -1.737677 -1.013974
3 -1.352219 -0.117969  0.375469
4  0.104815  1.686209  1.415251

weight     1
entropy    1
size       2
dtype: int64

    entropy      size    weight
0  0.547441  0.193912  1.162001
1 -0.667286 -1.289521 -1.398634
2 -1.013974 -3.475354  0.864093
3  0.375469 -0.235939 -1.352219
4  1.415251  3.372418  0.104815


In [20]:
print(df.index)
print(df.columns)
print(df.values)
print(type(df.values))

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=3, step=1)
[[ 0.02956917  1.43777838  2.48011121]
 [ 0.38976956  0.5711733  -0.44538652]
 [-1.68713377  0.25834374  0.91158027]
 [-0.63219733 -0.95991771 -0.5139165 ]
 [ 0.28474655  0.26286086 -0.79172293]]
<class 'numpy.ndarray'>


In [57]:
print(df.describe())
print(type(df.describe()))
# help(pd.period_range)

          money      time    reward
count  5.000000  5.000000  5.000000
mean   0.338331  0.472040  0.257123
std    1.027186  1.660097  1.359074
min   -0.628995 -1.547222 -1.364060
25%   -0.223191 -1.130512 -0.940734
50%   -0.124213  1.618601  0.529012
75%    0.712479  1.703934  1.470163
max    1.955577  1.715397  1.591232
<class 'pandas.core.frame.DataFrame'>


In [24]:
df = pd.DataFrame(np.random.randn(5,3), index=list('ABCDE'), columns=['money', 'time', 'reward'])
df

money      time    reward
A  0.469530 -1.066536 -1.032034
B  1.848790 -1.109587  0.014415
C -0.542110 -0.863753 -0.797467
D -0.446204  0.073051 -0.249687
E -0.229727 -2.385274  0.196886

In [55]:
print(df.loc[:'C',['time', 'reward']])
print()
# print(df['A']) ERROR
print (df[1:2])
print()
print (df.loc['A'])
print()
print (df.iloc[1:4])

       time    reward
A  1.703934  1.591232
B -1.130512  1.470163
C  1.715397 -0.940734

      money      time    reward
B  0.712479 -1.130512  1.470163

money     1.955577
time      1.703934
reward    1.591232
Name: A, dtype: float64

      money      time    reward
B  0.712479 -1.130512  1.470163
C -0.223191  1.715397 -0.940734
D -0.628995 -1.547222  0.529012


In [29]:
print(len(df))
print(df.shape[0])
print(df.shape[1])
print(np.arange(2, 5))
print(np.zeros(2,))

5
5
3
[2 3 4]
[0. 0.]


In [33]:
td = {('a', 'b'): 1, ('a', 'a'): 2}
pprint.pprint(td)
pprint.pprint(td[('a', 'b')])

{('a', 'a'): 2, ('a', 'b'): 1}
1
